services:
  # ------------------------------------------------------------
  # PostgreSQL
  # ------------------------------------------------------------
  postgres:
    image: postgres:16
    container_name: bluepay_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: offlinepay
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    restart: always

  # ------------------------------------------------------------
  # Flask Wallet Service
  # ------------------------------------------------------------
  wallet-service:
    build: ./wallet_service
    container_name: bluepay_wallet_service
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    env_file:
      - ./wallet_service/.env
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    command: flask run
    volumes:
      - ./wallet_service:/app
    restart: on-failure

volumes:
  pg_data:
